### ISSUE TITLE
Is use of deprecated ApplicatioinListeners to handle close/quit events limiting us to old versions of the JDK ?

### ISSUE THREAD

**Issue by kesterlester** [svenmeier/jorgan#5]
In my first attempts to build Jorgan on my mac I built against the jdk-16.0.2.jdk  that Oracle presented me with as the default/current for my system.

Though building was successful, at run-time it became apparent that Jorgan was attempting to use some JDK interfaces which had been deprecated some years ago, and which had been in fact entirely removed prior to the release of jdk-16.0.2.jdk.  Consequently Jorgan would crash on attempting to open (some) dispositions.

Having seen some hints on https://jorgan.info/base/m/Mac.html that (perhaps) only JDK version up to 11 were supported I went away and downloaded  jdk-11.0.12.jdk .  [This proved to be much harder than I thought it would be, as Oracle have made the task of getting hold of older version far harder than it needs to be on account of licensing issues ... but that's another story. ]

Building against JDK ver 11 succeeded (just as the build against JDK ver 16 had done) --- but with the added bonus this time that the program now ran properly as the deprecated interfaces Jorgan was using were/are not removed in this earlier JDK.

OK - so far so good.

My main thought, then, is would it be a good idea to remove the use of the deprecated interfaces so that users don't have to jump through hoops to find old versions of the JDK ?   Of course, I could be wrong in assuming that the interface changes from JDK-11 to JDK-16 were the *only* things which one might need to fix to get support moved to JDK-16.  I.e. perhaps there are other problems I didn't see.

But anyhow, in case it's useful, the main problem that I *did* see were all related to the MacAdapter "getInstance()" method in 

`./jorgan-gui/src/main/java/jorgan/swing/MacAdapter.java`

being called by an OrganFrame:

`./jorgan-gui/src/main/java/jorgan/gui/OrganFrame.java`

Essentially, line 204 of MacAdapter's getInstance() method:

https://github.com/svenmeier/jorgan/blob/12c62e51c1585033daffcfa689bee25b4921a00d/jorgan-gui/src/main/java/jorgan/swing/MacAdapter.java#L203

is supposed to do this:

`adapter = new Real();`

but instead throws an exception (which is caught) resulting in the adapter instead being set to a dummy adapter pin line 207 :
https://github.com/svenmeier/jorgan/blob/12c62e51c1585033daffcfa689bee25b4921a00d/jorgan-gui/src/main/java/jorgan/swing/MacAdapter.java#L207

The cause of the throwing is that the Real() class being instantiated ( definition beginning at https://github.com/svenmeier/jorgan/blob/12c62e51c1585033daffcfa689bee25b4921a00d/jorgan-gui/src/main/java/jorgan/swing/MacAdapter.java#L101 ) tries to add "ApplicationListeners" to handle window close events.  According to

https://stackoverflow.com/questions/9239287/what-is-the-alternative-for-deprecated-com-apple-eawt-applicationlistener/28090946

the handling of close/quit events is supposed to be handled not by Application Listeners but by calls to 

```
com.apple.eawt.Application.setQuitHandler()      //, and
com.apple.eawt.Application.setQuitStrategy()
```

Someone who faced a need to fix a different program facing a need to transition from the old to the new interfaces  wrote up their experience here:

https://discourse.processing.org/t/error-hello-processing-jdk-10-osx-high-sierra-com-apple-eawt-quithandler-not-supported/1396/3

However, unfortunately, despite staring at what's going on I don't feel able to see how to fix the issue myself.

Again, this may not be the ONLY fix needed to avoid being stuck on JDK 11 forever, but I am willing to help test potential improvements in this area.

**Comment by kesterlester** [comment]
I just stumbled across two links which might help someone trying to address the above. The first link is this:

https://alvinalexander.com/java/java-mac-osx-about-preferences-quit-application-adapter/

which was  mostly written before the deprecation kicked in (but has some notes added after the author was informed of the deprecation). The second link is the above author's response to the deprecation and it is found here:

https://alvinalexander.com/source-code/java-macos-about-preferences-quit-handlers-desktop-awt/

**Comment by svenmeier** [comment]
Thanks for reporting this issue.

I've pushed an update that moves to the new API.  Could you give it a try?

**Comment by kesterlester** [comment]
OK - I will give it a go.

**Comment by kesterlester** [comment]
OK - first preliminary test from me (this is deliberately switching back to SDK 16) is that I still get an exception when the MacAdapter is instantiated, BUT the cause of it is different now -- it's a:

`java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler`

error, which I've not yet had time to debut, but (maybe?) it could just turn out to be something that just needs an extra jar file added the the class path in run.sh ?  Or in some other aspect of the build?  Again, I wish I had more experience of ant/java.  Full error message below. I have to go home now to see my wife and kids, but I can look again in a few hours to see if either (a) I can implement any suggestions you may have, or (b) I can see if I can fix the error message below myself.

```
Christophers-M1:sources lester$ ./run.sh 
Aug 16, 2021 5:47:53 PM jorgan.Version log
INFO: jOrgan null
os.arch = x86_64
os.name = Mac OS X
os.version = 11.4
java.home = /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home
java.version = 16.0.2
java.runtime.name = Java(TM) SE Runtime Environment
java.runtime.version = 16.0.2+7-67
user.dir = /Users/lester/JORGAN/sources
user.home = /Users/lester
user.country = GB
user.language = en
user.name = lester
Aug 16, 2021 5:47:54 PM jorgan.gui.LAF install
INFO: setting look and feel 'com.apple.laf.AquaLookAndFeel'
LESTER 1
LESTER 3
Aug 16, 2021 5:47:56 PM jorgan.swing.MacAdapter unexpected
WARNING: unexpected failure
java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler
	at jorgan.swing.MacAdapter.getInstance(MacAdapter.java:173)
	at jorgan.gui.OrganFrame.<init>(OrganFrame.java:142)
	at jorgan.gui.GUI$FrameInit.run(GUI.java:149)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:306)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 16 more

LESTER 4
LESTER 5
LESTER 8
LESTER 8
LESTER 8
LESTER 8
```

which also shows some output from print statements I inserted here:

```
        /**
         * Get the global instance.
         * 
         * @return instance
         */
        public static MacAdapter getInstance() {
                if (adapter == null) {
                        if (isMac()) {
                                try {   
                                        System.out.println("LESTER 1");
                                        adapter = new Real();
                                        System.out.println("LESTER 2");
                                } catch (Throwable throwable) {
                                        System.out.println("LESTER 3");
                                        unexpected(throwable);
                                        System.out.println("LESTER 4");

                                        adapter = new Dummy();
                                        System.out.println("LESTER 5");
                                }
                        } else {
                                        System.out.println("LESTER 6");
                                adapter = new Dummy();
                                        System.out.println("LESTER 7");
                        }
                }
                                        System.out.println("LESTER 8");
                return adapter;
        }
```

**Comment by svenmeier** [comment]
Ah, just noticed that there is a replacement for this in Java's standard Desktop class now.

I've pushed another change.

**Comment by kesterlester** [comment]
After a bit more looking I note that the class that is not being found is called
com/apple/eawt/QuitHandler
while a class called 
java.awt.desktop.QuitHandler
seems to be what's there

**Comment by kesterlester** [comment]
Just abandoned what I was writing as I figured that you might be saying the same thing (or something better). I will look at your latest update.

**Comment by kesterlester** [comment]
OK - good news (mostly).

With your latest push I can compile against both JDK 11 and JDK 16 on mac.

The JDK 11 version still works. [i.e. I can play the "fluidsynth-example" disposition and a "BALMAIN_j320_fs" disposition I downloaded from the web as a test].

The JDK 16 version is still broken, in the sense that you can start up Jorgan ok (this time without any complaints about MacAdapters, so that's an improvement) and get to the basic opening view. However if I then try to open (any?) disposition I get a crash with messages like those pasted below. Still, though that means one still cannot use JDK 16, it still feels like an improvement:

```
Christophers-M1:sources lester$ ./run.sh 
Aug 16, 2021 8:21:50 PM jorgan.Version log
INFO: jOrgan null
os.arch = x86_64
os.name = Mac OS X
os.version = 11.4
java.home = /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home
java.version = 16.0.2
java.runtime.name = Java(TM) SE Runtime Environment
java.runtime.version = 16.0.2+7-67
user.dir = /Users/lester/JORGAN/sources
user.home = /Users/lester
user.country = GB
user.language = en
user.name = lester
Aug 16, 2021 8:21:50 PM jorgan.gui.LAF install
INFO: setting look and feel 'com.apple.laf.AquaLookAndFeel'
Aug 16, 2021 8:22:01 PM jorgan.gui.GUI$ExceptionInit uncaughtException
SEVERE: unexpected
java.lang.Error: Unable to make void java.awt.EventDispatchThread.pumpEvents(java.awt.Conditional) accessible: module java.desktop does not "opens java.awt" to unnamed module @13545af8
	at spin.off.AWTReflectDispatcherFactory.<clinit>(AWTReflectDispatcherFactory.java:144)
	at spin.off.SpinOffEvaluator.<clinit>(SpinOffEvaluator.java:38)
	at spin.Spin.<clinit>(Spin.java:68)
	at jorgan.gui.OrganFrame.setSession(OrganFrame.java:305)
	at jorgan.gui.OrganFrame.openOrgan(OrganFrame.java:358)
	at jorgan.gui.OrganFrame$RecentAction.actionPerformed(OrganFrame.java:447)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
	at java.desktop/com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.menuDragMouseReleased(BasicMenuItemUI.java:1134)
	at java.desktop/javax.swing.JMenuItem.fireMenuDragMouseReleased(JMenuItem.java:575)
	at java.desktop/javax.swing.JMenuItem.processMenuDragMouseEvent(JMenuItem.java:472)
	at java.desktop/javax.swing.JMenuItem.processMouseEvent(JMenuItem.java:417)
	at java.desktop/javax.swing.MenuSelectionManager.processMouseEvent(MenuSelectionManager.java:347)
	at java.desktop/javax.swing.plaf.basic.BasicPopupMenuUI$MouseGrabber.eventDispatched(BasicPopupMenuUI.java:903)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2184)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2076)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2075)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2075)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2032)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Co
```

**Comment by svenmeier** [comment]
This is the first time I've tried Java 16. The new Java module system is mandatory now,  i.e. access to AWT internals is no longer possible.

For an easy workaround I just added the `--illegal-access=permit` option, see my new commit. I will have to find a better solution later.

**Comment by kesterlester** [comment]
Hey! Success!  Your recent changes appear to get the BALMAIN_j320_fs working with Java 16 now!  

As you might guess given your last comment, there are some grumblings (Warnings) about the above flag, but it works.

```
Christophers-M1:sources lester$ 
Christophers-M1:sources lester$ 
Christophers-M1:sources lester$ ./run.sh 
Java HotSpot(TM) 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
Aug 16, 2021 11:42:06 PM jorgan.Version log
INFO: jOrgan null
os.arch = x86_64
os.name = Mac OS X
os.version = 11.4
java.home = /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home
java.version = 16.0.2
java.runtime.name = Java(TM) SE Runtime Environment
java.runtime.version = 16.0.2+7-67
user.dir = /Users/lester/JORGAN/sources
user.home = /Users/lester
user.country = GB
user.language = en
user.name = lester
Aug 16, 2021 11:42:07 PM jorgan.gui.LAF install
INFO: setting look and feel 'com.apple.laf.AquaLookAndFeel'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by spin.off.AWTReflectDispatcherFactory (file:/Users/lester/JORGAN/sources/jorgan-gui/lib/spin-1.5.jar) to method java.awt.EventDispatchThread.pumpEvents(java.awt.Conditional)
WARNING: Please consider reporting this to the maintainers of spin.off.AWTReflectDispatcherFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by svenmeier** [comment]
Many thanks for testing.
